### ISSUE TITLE
share image does not work

### ISSUE THREAD

**Issue by drawapp8** [robnyman/Firefox-OS-Boilerplate-App#12]
Pick an image and share it, select "Wallpaper", the preview window is empty.

**Comment by robnyman** [comment]
I'll look into this and will get back to you.

**Comment by robnyman** [comment]
This has now been fixed: https://github.com/robnyman/Firefox-OS-Boilerplate-App/blob/gh-pages/js/webapp.js#L147

**Comment by drawapp8** [comment]
Thank you very much.
