### ISSUE TITLE
i18n by default

### ISSUE THREAD

**Issue by gmarty** [robnyman/Firefox-OS-Boilerplate-App#13]
I'd love to get a basic i18n layer in this boilerplate app, just to get me started with translating apps.
It's still unclear to me what is the best practice when it comes to i18n-ing Firefox OS apps, if any.

**Comment by robnyman** [comment]
Localizing in general for Firefox OS is described at https://developer.mozilla.org/en-US/docs/Localizing_Firefox_OS
I'll set something up for the Boilerplate App so we can have support for several languages.

I'll get back to you on this. :-)

**Comment by robnyman** [comment]
We put together an article at Mozilla Hacks around this: https://hacks.mozilla.org/2013/08/localizing-firefox-os-apps/
The scope/code needed might be a bit too complex for the intended simplicity of the Boilerplate, so I'll leave it out for now.
