### ISSUE TITLE
Privileged apps does not work

### ISSUE THREAD

**Issue by laukstein** [robnyman/Firefox-OS-Boilerplate-App#14]
Firefox OS Simulator 3.0.1 returns

> **File not found**
> Firefox can't find the file at app://9ae0db53-4940-46e4-a500-f20cb7aba03b/app/."
> 
> Content JS ERROR at app://homescreen.gaiamobile.org/js/page.js:161 in icon_fetchImageData: Got an exception when trying to load icon "app://9ae0db53-4940-46e4-a500-f20cb7aba03b/app/images/logo64.png", falling back to cached icon. Exception is: [Exception... "File error: Not found"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: app://homescreen.gaiamobile.org/js/page.js :: icon_fetchImageData :: line 158"  data: no]

Firefox OS Simulator Dashboard errors:

> **Packaged App**
> Validation Result: WARNINGS (0 errors and 1 warnings)
> Warnings: Denied permission 'bluetooth' for type 'privileged'.
> 
> **Hosted App**
> Validation Result: INVALID (1 errors and 0 warnings)
> Errors: Hosted App can't be type 'privileged'.

Pushing on device packaged app, shows alert "App installed", but actually it did not install it and app icon does not shows up on screen. And on pushing hosted app, nothing happens at all.

The **manifest.appcache** additions 

```
"type": "privileged",
"permissions": {
    "bluetooth": {}
}
```

I tried also to add also CSP header for **index.php**, but it did not help ether

```
header("Content-Security-Policy: default-src *; script-src 'self'; object-src 'none'; style-src 'self' 'unsafe-inline'");
```

Any solution or reported bug for it?

**Comment by robnyman** [comment]
So, many questions. :-)
First, Bluetooth is only available as a certified API right now, i.e. for Mozilla and the OS: https://developer.mozilla.org
/en-US/docs/Web/Apps/App_permissions?redirectlocale=en-US&redirectslug=Apps%2FApp_permissions

Icons are relative to the app's own path, so try different combinations for packaged vs. hosted apps.

The app does get installed, but on the build I assume you have, you need to restart the phone after the first push to see the actual app.

**Comment by laukstein** [comment]
@robnyman, thanks for your feedback! How currently I can make own certified app on using permissions like bluetooth? Is it possible?

**Comment by robnyman** [comment]
Currently only Mozilla can do privileged apps, due to security concerns. So, right now you can't access Bluethooth although you could use [Web Activities](https://hacks.mozilla.org/2013/01/introducing-web-activities/) to trigger something that in turn uses Bluetooth, but with user approval first.

**Comment by laukstein** [comment]
Thanks for the link!
It seems that currently FirefoxOS does not handle any certified app permissions, and will return `null`.
Any better documentation for Web Activities?
Is there any API to access device unique ID, phone number, etc.?

**Comment by robnyman** [comment]
As mentioned above, you can't get certified access, that's reserved for Mozilla.
And no, no API for unique ID, phone number etc.
