### ISSUE TITLE
Remove master branch

### ISSUE THREAD

**Issue by zenorocha** [robnyman/Firefox-OS-Boilerplate-App#17]
There's no need for maintaining a `master` branch.
1. Go ahead and make `gh-pages` as the default one
   
   ![](http://zno.io/R2gS/change-branch.gif)
2. Then remove `master`.
   
   ```
   git push origin :master
   ```

**Comment by robnyman** [comment]
I don't maintain a master one - and I agree. I've kept it just in case. The comment in the other thread was just more about the idea of having two branches with different manifest files/paths. I'll keep it for now, though, in case I want to use it for any specific purpose.
