### ISSUE TITLE
FirefoxOS Marketplace can not validate the manifest.webapp

### ISSUE THREAD

**Issue by FedericoElles** [robnyman/Firefox-OS-Boilerplate-App#22]
I went to 
https://marketplace.firefox.com/developers/validator
and entered your manifest:
http://robnyman.github.io/Firefox-OS-Boilerplate-App/manifest.webapp
which resulted in:

Your app failed validation with 1 error and 2 message(s).
`launch_path` must be a path relative to app's origin.
60x60px icon should be provided for Firefox OS.
App name may be truncated on Firefox OS devices.

**Comment by robnyman** [comment]
It is because it has been adapted to running packaged apps in the Firefox OS Simulator. The launch_patch will be relative for how you will be using it.
