### ISSUE TITLE
+ install looks like it works in Firefox 23 on Ubuntu, but doesn't

### ISSUE THREAD

**Issue by skierpage** [robnyman/Firefox-OS-Boilerplate-App#23]
I'm running Mozilla Firefox 23.0 on Ubuntu 13.04. Clicking "the + button in the top right corner to install this app" gave me a plain notification saying, roughly, "Firefox OS Boilerplate was installed" (yay!), and I can now launch "Firefox OS Boilerplate App" from the Unity launcher (yay!), but the new window that appears shows

   404
There isn't a GitHub Page here.

the same error page I get if I visit https://bad.github.com/

I realize this is probably various limitations of web apps/Firefox/Ubuntu rather than your fine demo app, but it feels close to working :smile:

**Comment by robnyman** [comment]
The general idea is to install it and run it in the Firefox OS Simulator. Most developers install it as packaged apps there, so the launch_path has been changed to work there (meaning it won't work out of the box at the GitHub page). Best way to try it is rather to download/pull the source, and then alter it locally according to your needs.

Hope that helps!
