### ISSUE TITLE
Broken link to Firefox OS app icons style guide on README

### ISSUE THREAD

**Issue by jaydson** [robnyman/Firefox-OS-Boilerplate-App#27]
Seems like the icons style guide page was moved.

**Comment by robnyman** [comment]
Fixed, thanks! Apparently someone decided to add a dash (-) to the URL.

**Comment by jaydson** [comment]
![](http://media.giphy.com/media/7PwOZJLNYUkU/giphy.gif)

**Comment by robnyman** [comment]
:-D
