### ISSUE TITLE
No way for user to return to app after clicking external links

### ISSUE THREAD

**Issue by christi3k** [robnyman/Firefox-OS-Boilerplate-App#30]
Currently there is no way for the user to return to the app after clicking external links while using the Boilerplate on the phone or in the simulator.

Possible solutions:

1) Add chrome navigation to manifest:
https://developer.mozilla.org/en-US/Apps/Developing/Manifest#chrome
(only works in >= 1.1)

2) Launch link via browser instead of in-app
(If possible.)

**Comment by robnyman** [comment]
Third option: adding <base target="_blank">. Just did and commited it.
