### ISSUE TITLE
There´s no "Developer mode" setting

### ISSUE THREAD

**Issue by SunboX** [robnyman/Firefox-OS-Boilerplate-App#4]
I want to install a privileged package. It installs fine without "privileged", but with this config the install fails. So I wanted to turn on "Developer mode", but there´s no setting menu for it.

So how to turn on Developer mode?

![Bildschirmfoto 2013-02-10 um 18 21 04](https://f.cloud.github.com/assets/83344/143451/5010bb72-73a6-11e2-8168-8fa7d013c5fd.png)
![Bildschirmfoto 2013-02-10 um 18 21 15](https://f.cloud.github.com/assets/83344/143452/549aa1e4-73a6-11e2-9d9c-c2f526e9695f.png)

**Comment by robnyman** [comment]
It was available in version 1.1pre3 of the Simulator. Unfortunately, it seems to have been taken out at the moment.
You can get that version from the [list of all Simulator versions](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/) - hopefully it works as expected for you.

**Comment by SunboX** [comment]
Oh, great! Thanks for the feedback! I really need this, I want to save images to the local file system. This API requires "privileged" right. Without this "Developer mode" I can't test anything :/

Thanks for your Feedback! :+1:

**Comment by SunboX** [comment]
Maybe this should be mentioned in your Readme. ;) took me some hours ...

**Comment by robnyman** [comment]
Yeah… Problem is that it's all in flux and it _should_ be in there to enable, so I'm trying to figure out what's happening.

**Comment by SunboX** [comment]
*g ok, thanks for your help! And good luck! (really ;))

**Comment by robnyman** [comment]
Thanks, I think it's needed. :-)

**Comment by SunboX** [comment]
hm, doesn´t really work ... switched "Developer mode" on ... but install fails with message "Bessa Install failed". Without the `"type": "privileged",`it installs fine. But as far as I try to store an image, I get a "SecurityError".

my manifest looks like:

``` javascript
{
    "name": "Bessa",
    "description": "Bessa - the Image Editor",
    "version": "xxx",
    "launch_path": "/bessa-app/release/index.html",
    "developer": {
        "name": "André Fiedler",
        "url": "http://bessa-app.com/"
    },
    "installs_allowed_from": ["*"],
    "activities": {
        "open": {
            "filters": {
                "type": ["image/png", "image/jpg", "image/jpeg"]
            },
            "href": "/bessa-app/release/index.html",
            "disposition": "window"
        }
    },
    "type": "privileged",
    "permissions": {
        "device-storage:pictures": {
            "description": "Required for saving images",
            "access": "readwrite"
        }
    },
    "locales": {
        "en": {
            "name": "Bessa",
            "description": "Bessa - the Image Editor"
        },
        "de": {
            "name": "Bessa",
            "description": "Bessa - Bessere Bilder"
        }
    },
    "default_locale": "en",
    "icons": {
        "16": "/bessa-app/release/style/icons/16/Bessa.png",
        "32": "/bessa-app/release/style/icons/32/Bessa.png",
        "48": "/bessa-app/release/style/icons/48/Bessa.png",
        "64": "/bessa-app/release/style/icons/64/Bessa.png",
        "128": "/bessa-app/release/style/icons/128/Bessa.png"
    }
}
```

**Comment by robnyman** [comment]
In that case, I'm sorry. Then it won't work with the Simulator at the moment. One option is to upload it to the [Firefox Marketplace](https://marketplace.firefox.com/) and install it from there. Or try the experimental approach of [b2gremote](https://github.com/fabricedesre/b2gremote).

**Comment by SunboX** [comment]
I got it working with Simulator 2.0. You need to install it via Firefox OS Simulator Dashboard (!), because that's the only way you can test "privileged" apps by now. I tried the JavaScript installPackage() all the time. that doesn´t work. I don´t know why.

**Comment by robnyman** [comment]
Yes, that should work. I plan to look into installPackage and what the actual options are. Thanks for the update!
