### ISSUE TITLE
New Gaia Style

### ISSUE THREAD

**Issue by Mte90** [robnyman/Firefox-OS-Boilerplate-App#44]
In Firefox OS 1.2 Gaia have a flat graphic and in the boilerpalte exist only the style of older versions.Iit's possible add a second folder with the new graphic? So the developer can choose the graphic or add a code that check the Firefox OS version and load the correct Gaia style.

**Comment by robnyman** [comment]
If you want to issue a pull request with the updated looks, I'd be more than happy to accept it! I'd recommend replacing rather than having several options in the repository, though.

**Comment by Ryuno-Ki** [comment]
I'm against replacing, since Alcatel users will have to stick on Firefox OS v1.1 until April due to Alcatel's policy.

So maybe storing the new UI in another branch? I know, it increases the work for maintenance …

**Comment by robnyman** [comment]
I don't think it's worth that maintenance/dual code. Since this isn't mainly meant as a design template for Firefox OS app development, but rather showing APIs, Web Activities etc, I think one will do fine. Over time, when we will have Firefox OS 1.1, 1.2, 1.5, 2.0 etc out there, having separate design packages for all will probably not make things easier for developers either.

**Comment by Mte90** [comment]
My idea is to insert two graphic version and load it after a check of the firefox os version.
In this way the user not have a strange graphic that don't know.

**Comment by robnyman** [comment]
That works now, but it's an extra check, and when we have more versions, it won't hold. I'd prefer just updating it, to be honest.

**Comment by Ryuno-Ki** [comment]
> Since this isn't mainly meant as a design template for Firefox OS app development, but rather showing APIs, Web Activities etc, I think one will do fine.

Oh, I wasn't aware of that. Okay, in case it's only meant as show case, the design won't matter.

**Comment by robnyman** [comment]
No worries. I think if it looks like Firefox OS apps it's an upside, but not a necessity. The JavaScript code specifically is the important part, I'd say.

**Comment by robnyman** [comment]
I'm closing this issue for now. @Mte90 feel more than welcome to issue a pull request with updated Gaia looks.

**Comment by Mte90** [comment]
https://github.com/buildingfirefoxos/Building-Blocks i think of use this css.
i'm undecided if insert all css in the boilerplate or remove the things not used in the boilerplate.

**Comment by robnyman** [comment]
Well, the current version is based on that, from a while back. You could evaluate how much it is worth to include, and what makes most sense.
