### ISSUE TITLE
Unable to install via FFox App Manager

### ISSUE THREAD

**Issue by kkruups** [robnyman/Firefox-OS-Boilerplate-App#49]
Error indicated below when selecting Add Hosted App menu option to install application.
## Error Msg

The webapp manifest isn't a valid JSON file: SyntaxError: JSON.parse: unexpected character at: http://robnyman.github.io/Firefox-OS-Boilerplate-App/

---

Steps:
1. Enter address "http://robnyman.github.io/Firefox-OS-Boilerplate-App/" in <Add Host App> field.

**Comment by kkruups** [comment]
Additional Detail: Reported issue while connected to 1.3 Firefox Simulator

**Comment by robnyman** [comment]
Thanks for the heads-up! This is related to paths in the manifest file in conjunction with the App Manager, and also that most developers clone the repo and install it as a packaged app. I've updated the instructions. Basically, you need to add another URL to have it as a hosted app in the App Manager: http://robnyman.github.io/Firefox-OS-Boilerplate-App/manifest-hosted.webapp
