### ISSUE TITLE
Install failed with INVALID_SECURITY_LEVEL

### ISSUE THREAD

**Issue by vuldin** [robnyman/Firefox-OS-Boilerplate-App#5]
I get an error when attempting to install this app on the latest Firefox OS build. The error is:

Install failed
:INVALID_SECURITY_LEVEL

I'm trying install by clicking the + icon from the website:
http://robnyman.github.com/Firefox-OS-Boilerplate-App/

I'm not sure if this issue shows up when trying to install in other versions of Firefox OS.

**Comment by robnyman** [comment]
Ah, I just pushed a new manifest asking for privileged access (which only works if installed as a privileged app, which the + icon doesn't trigger). I've removed those parts, and it should work as expected now. Let me know how it goes!
