### ISSUE TITLE
Click on + install the app with the wrong url

### ISSUE THREAD

**Issue by Mte90** [robnyman/Firefox-OS-Boilerplate-App#51]
If you install the app with the plus button the path of the app it's wrong.
The url is http://robnyman.github.io/index.html, i think to add a check if hosted or packaged and load the corect manifest.

**Comment by Mte90** [comment]
The code for install the app with the plus button it's used only when the app it's used with the browser.
The pull change the path of the manifest in base.js.

**Comment by robnyman** [comment]
Great, thanks! Updated this repo as well.
