### ISSUE TITLE
bn-BD localization is not present

### ISSUE THREAD

**Issue by rabbihossain** [robnyman/Firefox-OS-Boilerplate-App#54]
We completed localizing the app in bn-BD locale. But it is not added in this repo. Why it's not added? Do we need to do some more things?

**Comment by robnyman** [comment]
Hmm, interesting. It should've been added from Transifex to this repo when I got the latest version from there. I'll look into it.

**Comment by rabbihossain** [comment]
thanks. If possible remind us in this thread. :)

**Comment by robnyman** [comment]
Following up on this. Not sure why it wasn't automatically added, so I added it manually now. [Commit](https://github.com/robnyman/Firefox-OS-Boilerplate-App/commit/bcb025bfedf04fe833647d6ab9824f5886845409).
