### ISSUE TITLE
New l10n.js library

### ISSUE THREAD

**Issue by Mte90** [robnyman/Firefox-OS-Boilerplate-App#57]
The l10n.js librabry is updated:
http://informationisart.com/26/
It's retro compatible.

Is possible update the version of the boilerplate?

**Comment by robnyman** [comment]
Thanks! We'll need to investigate what it means and if its backwards compatible with what we use in the Boilerplate.

**Comment by robnyman** [comment]
Updated to the new version of l10n.js from Gaia: [commit](https://github.com/robnyman/Firefox-OS-Boilerplate-App/commit/6af94994b81a227c8e74cea43cba90b6a799dcb6). Tested and seems to be working fine - please let me know if you encounter any issues.
