### ISSUE TITLE
MANIFEST_URL_ERROR when publishing similar app

### ISSUE THREAD

**Issue by matheusjardimb** [robnyman/Firefox-OS-Boilerplate-App#58]
I've playing with this boilerplate app and just ziped my version. The problem is that my app got rejected and I just can't fix it: when user try to install it through FFOS Marketplace, the message "App install error: MANIFEST_URL_ERROR" appears.

Any tip? This sample app should be facing the same problem.

**Comment by Mte90** [comment]
Sometimes this problem is Firefox that have some bug with the environment.
Have you tried on other pc?

**Comment by matheusjardimb** [comment]
Yep. This is the app address. https://marketplace.firefox.com/app/white-noise-player/ Can you install it? 
It's a simple white noise player. I'm using windows

**Comment by Mte90** [comment]
this app is not public, if the app is in the marketplace it's not a problem of the boilerplate

**Comment by matheusjardimb** [comment]
I'm really new to FFOS. Possibly I'm missing something. Is this project published as an app? Or any other app based on this project? I'm just curious to know... thanks!

**Comment by Mte90** [comment]
It's a boilerplate it's not in the marketplace :-)

**Comment by matheusjardimb** [comment]
@Mte90  you're totally right! The app just became installable... https://marketplace.firefox.com/app/white-noise-player/ - FFOS marketplace had a really weird behavior... Thanks for all your help!

**Comment by matheusjardimb** [comment]
Feel free to close the issue

**Comment by robnyman** [comment]
Glad to see that it worked out!
