### ISSUE TITLE
NFC example

### ISSUE THREAD

**Issue by Mte90** [robnyman/Firefox-OS-Boilerplate-App#60]
It's possible a NFC example?
I've a Flame but this page https://wiki.mozilla.org/WebAPI/WebNFC it's very complicate.

**Comment by robnyman** [comment]
It would be nice to have one, for sure. I'll look into it as soon as I get the chance!

**Comment by robnyman** [comment]
I've talked to the developers, and right now it's only a Certified API (meaning that regular developers can't use it). The plan is to make it Privileged, but we're not there yet. I'll close this for now, but if it becomes Privileged, we should definitely have examples for it!

**Comment by Mte90** [comment]
Mozilla release phones with NFC and then is not freely usable API -.-'

**Comment by robnyman** [comment]
Initially its in Certified apps, but yes, the intention is to make it available for everyone.
