### ISSUE TITLE
Webapp manifest isn't valid

### ISSUE THREAD

**Issue by nazrdogan** [robnyman/Firefox-OS-Boilerplate-App#61]
The webapp manifest isn't a valid JSON file: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data at: http://localhost:63342/Firefox-OS-Boilerplate-App-gh-pages/index.html

**Comment by Mte90** [comment]
Uhm i think that you have added an index.html file not a manifest.webapp file.

**Comment by nazrdogan** [comment]
ok I solved my issue .Yesterday I was sleepy I cant recoginize problem :) .and I solved load packaged app.thank you

**Comment by robnyman** [comment]
Thanks @Mte90! :-) Glad it worked out.
