### ISSUE TITLE
Marketplace Web Activity examples

### ISSUE THREAD

**Issue by Mte90** [robnyman/Firefox-OS-Boilerplate-App#62]
https://github.com/mozilla/fireplace/wiki/Web-Activities#marketplace-app-rating
In this url there are few example about web activity of the marketplace app. I think that the examples are a good idea in this boilerpalte for promote the apps.

**Comment by robnyman** [comment]
Thanks for the suggestion. Still contemplating this and if/how to best do it.

**Comment by robnyman** [comment]
I tried using the more general ones that aren't connected to a certain app (like Marketplace search, Category etc) but nothing happens in the Simulator for Firefox OS 1.4 or 2.1 and no errors in the console. Wonder if these still work…

**Comment by robnyman** [comment]
After more research, apparently it's a [bug in the Simulator](https://bugzilla.mozilla.org/show_bug.cgi?id=1075440). I'll await for that one to be fixed first.

**Comment by robnyman** [comment]
Given that it doesn't seem this will be fixed soon, I'm closing this. I'm all for having it reopened when the Simulator is more stable in this aspect.
