### ISSUE TITLE
fxosRate integration

### ISSUE THREAD

**Issue by Mte90** [robnyman/Firefox-OS-Boilerplate-App#63]
```
fxosRate is a Library to help the promotion of your Firefox Marketplace apps by encouraging application users to rate the application. The library decides when it's the best moment to ask users to rate the app based on a set of parameters.
```

Also support l0n.js
https://github.com/dcoloma/fxosRate

Maybe is an useful library to integrate in the boilerplate.

**Comment by robnyman** [comment]
Thanks for the suggestion. I think this is interesting, but the goal with the Boilerplate is more to have core API and Activites functionality than libraries to promote your app in one specific app store.

**Comment by Mte90** [comment]
Maybe add a section in the readme with some useful resources like this?
Is useful for those who approach for the first time in the development of Firefox OS

**Comment by robnyman** [comment]
I think that sounds like a better fit for the [App Center on MDN](https://developer.mozilla.org/en-US/Apps). You should add it there in a good place!

**Comment by Mte90** [comment]
Usually the boilerplate are solutions ready for use from scratch and the people not see the wiki for this library.

**Comment by robnyman** [comment]
That is true, but one key goal with the boilerplate is also to avoid any libraries (since the developers should choose for themselves), so if I start including/promoting one here, it sets a precedent for others.
Also, the App Center is referred from the README at the beginning, and hopefully people will go there to delve deeper.

**Comment by Mte90** [comment]
This is true for the promoting, maybe create a list in the wiki of the repo?

**Comment by robnyman** [comment]
I haven't used the wiki so far, so not sure it's the best start. Besides,
MDN gets a lot more views and have more people maintaining it, so it seems
better to have it in such a place.

**Comment by Mte90** [comment]
Uhm this is also true.
Maybe is a question for the mailing list for create a page with useful development resources on MDN.

**Comment by robnyman** [comment]
Yes, Chris Mills is working extensively on that, so please reach out to him
at Chris Mills cmills@mozilla.com

**Comment by Mte90** [comment]
Ta dah!
https://developer.mozilla.org/en-US/Apps/Reference/Firefox_OS_app_tools

**Comment by robnyman** [comment]
Great! :-)
