### ISSUE TITLE
Alarm API doesn't work

### ISSUE THREAD

**Issue by Gioyik** [robnyman/Firefox-OS-Boilerplate-App#7]
Hi,

I tested the template but the AlarmAPI buttom doesn't work. All looks correct, any idea? I tested on a Unagi device.

Regards

**Comment by robnyman** [comment]
Basically, the Alarm API doesn't really work as intended - it's more as a timer than an alarm clock. As it has been described to me, the idea is to be able to open an application at a given time.

I'll remove it from the Boilerplate for now, because I think it's more confusing than helping.

**Comment by Mte90** [comment]
it's possible add the alarm api now?

**Comment by robnyman** [comment]
Yeah, I think you're right, probably good to get it back in. I'll add it soon!

**Comment by nicokant** [comment]
I agree with Mte, it will be very useful!

**Comment by robnyman** [comment]
I promise I will get to it. Last week has been a bit… intense.

**Comment by nicokant** [comment]
no problem, thanks for your help!

**Comment by robnyman** [comment]
Thanks for your patience. :-)

**Comment by robnyman** [comment]
Sorry for taking some time with this. [Alarm API examples added now](https://github.com/robnyman/Firefox-OS-Boilerplate-App/commit/d90b99539456d606c945abde30a17f79e2496316).
