### ISSUE TITLE
Worng Parameter on "add contact" function

### ISSUE THREAD

**Issue by AitorC** [robnyman/Firefox-OS-Boilerplate-App#9]
In webapp.js:121 "familyName" should be instead "lastName", as for the latest Firefox OS Simulator.

_Note:_ The strange thing is, that inside internally it somehow calls it familyName, even though it expects a property called "lastName". As seen in contacts_form.js:254 of gaia: "familyName.value = params.lastName"

**Comment by robnyman** [comment]
Interesting. I'll talk to the engineers to find out which one it should be.

**Comment by robnyman** [comment]
Submitted a fix.
